NUTCH 2940 Develop Gradle Core Build for Apache Nutch
csci401-apache-nutch/nutch pull request #11
Opened 2022-04-11 05:38 UTC by jbsimmon

Added file collection variable for test classpath, and gradle tasks for ant targets compile, compile-core, proxy, benchmark. Also fixed a depends for previously renamed init-nutch.

Thanks for your contribution to [Apache Nutch](https://nutch.apache.org/)! Your help is appreciated!

Before opening the pull request, please verify that
* there is an open issue on the [Nutch issue tracker](https://issues.apache.org/jira/projects/NUTCH) which describes the problem or the improvement. We cannot accept pull requests without an issue because the change wouldn't be listed in the release notes.
* the issue ID (`NUTCH-XXXX`)
  - is referenced in the title of the pull request
  - and placed in front of your commit messages surrounded by square brackets (`[NUTCH-XXXX] Issue or pull request title`)
* commits are squashed into a single one (or few commits for larger changes)
* Java source code follows [Nutch Eclipse Code Formatting rules](https://github.com/apache/nutch/blob/master/eclipse-codeformat.xml)
* Nutch is successfully built and unit tests pass by running `ant clean runtime test`
* there should be no conflicts when merging the pull request branch into the *recent* master branch. If there are conflicts, please try to rebase the pull request branch on top of a freshly pulled master branch.

We will be able to faster integrate your pull request if these conditions are met. If you have any questions how to fix your problem or about using Nutch in general, please sign up for the [Nutch mailing list](https://nutch.apache.org/mailing_lists.html). Thanks!

2022-04-12 17:13 UTC, lewismc requested changes
See minor comment @jbsimmon thank you

2022-04-12 17:13 UTC, lewismc commented on build.gradle.kts
> +    file(project.properties["build.plugins"]), // plugins.classpath.dir
Please remove comment

2022-04-12 17:13 UTC, lewismc commented on build.gradle.kts
> +    // options.isOptimize = "${project.properties["javac.optimize"]}" == "on"
Yes please remove. See my comment on other PR and coordinate with @AzureTriple

2022-04-12 17:14 UTC, lewismc commented
Please merge once comment is addressed. Thanks

2022-04-21 19:19 UTC, jbsimmon commented
Addressed comments, can merge once someone reviews?

2022-04-21 22:11 UTC, merged